name: My First Action
on:
  # trigger manually
  workflow_dispatch:

jobs:
  create-keypair:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Verify aws
        run: aws --version

      - name: Configure AWS Credentials
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials
      
      - name: Verify AWS Credential
        run: aws configure list

      - name: Verify s3 permission
        run: aws s3 ls

      - name: Check out Repo to the runner
        uses: actions/checkout@v2

      - name: Verify main.tf
        run: cat main.tf

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        run: terraform init
        #env:
          #TF_ACTION_WORKING_DIR: /home/runner/work/KP-GHAction/KP-GHAction
          #AWS_ACCESS_KEY_ID:  ${AWS_ACCESS_KEY_ID}
          #AWS_SECRET_ACCESS_KEY:  ${AWS_SECRET_ACCESS_KEY}         
      
      #- name: Terraform Plan
       # uses: hashicorp/terraform-github-actions/plan@v0.4.0
        #env:
          #TF_ACTION_WORKING_DIR: /home/runner/work/KP-GHAction/KP-GHAction
         # AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
         # AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      
      #- name: Terraform Apply
      #  uses: hashicorp/terraform-github-actions/apply@v0.4.0
      #  env:
      #    TF_ACTION_WORKING_DIR: /home/runner/work/KP-GHAction/KP-GHAction
      #    AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 