name: Destroy-KeyPair

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Verify AWS
        run: aws --version
      
      - name: Configurate AWS Credential
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/credentials
        
      - name: Verify AWS Credentials
        run: aws configure
        
      - name: Copy main.tf to runner
        run: actions/checkout@v2
      
      - name: Terraform destroy
        run: terraform destroy